server:
  port: 8083
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  #activiti:
    #database-schema-update: true
    #check-process-definitions: true
    #process-definition-location-prefix: classpath:/processes
    #history-level: full
    #db-history-used: true
    #db-identity-used: true
#  level:
#    org:
#      springframework:
#        boot:
#          autoconfigure: INFO
mybatis:
  check-config-location: true
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/**/*Mapper.xml
  type-aliases-package: com.own.springboot.biz

