server:
  port: 8083
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
#logging:
#  level:
#    org:
#      springframework:
#        boot:
#          autoconfigure: INFO
mybatis:
  check-config-location: true
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/**/*Mapper.xml
  type-aliases-package: com.own.springboot.biz