#Async多线程创建线程池使用 ThreadPoolTaskExecutor
thread:
  pool:
    corePoolSize: 10
    maxPoolSize: 200
    queueCapicity: 10
#druid
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/specificdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: localuser
    password: localuser
    driver-class-name: com.mysql.jdbc.Driver
    jpa:
      show-sql: true
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 10
      validatin-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      use-global-data-source-stat: true
      stat:
        enabled: true
        db-type: oracle
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      slf4j:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: druid