
package com.own.springboot.biz.systemuser.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IwsServiceImpl", targetNamespace = "http://service.systemUser.biz.springboot.own.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IwsServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserList", targetNamespace = "http://service.systemUser.biz.springboot.own.com/", className = "com.own.springboot.biz.systemuser.service.GetUserList")
    @ResponseWrapper(localName = "getUserListResponse", targetNamespace = "http://service.systemUser.biz.springboot.own.com/", className = "com.own.springboot.biz.systemuser.service.GetUserListResponse")
    @Action(input = "http://service.systemUser.biz.springboot.own.com/IwsServiceImpl/getUserListRequest", output = "http://service.systemUser.biz.springboot.own.com/IwsServiceImpl/getUserListResponse")
    public List<Object> getUserList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
